# Generated by Django 5.2.15 on 2026-06-14 10:23

import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_status_4a0a95_idx',
            old_name='tasks_task_status_15f69d_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_priorit_a900d4_idx',
            old_name='tasks_task_priorit_4aa5ef_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_due_dat_bce847_idx',
            old_name='tasks_task_due_dat_986cce_idx',
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10, validators=[tasks.models.validate_priority]),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=10, validators=[tasks.models.validate_status]),
        ),
    ]
